---
name: Checks

On: [push]

jobs:
  test-lint:
  name: Test and Lint
  runs-on: ubuntu-lastest
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: docker-compose run --rm app sh -c "python manage.py test"
    - name: Lint
      run: docker-compose run --rm app sh -c "flake8"